### ISSUE TITLE
error bug install 

### ISSUE THREAD

**Issue by mikrotickets** [mendylivium/MendyVPN#1]
![image](https://user-images.githubusercontent.com/63126121/212798403-4ff246c2-739d-4d17-a0db-b6d9ba0f8c7c.png)

**Comment by mendylivium** [comment]
Your droplets is new ?
It should work on newly created droplets,

If you have existing Apache2, Mysql and PHP, just clone this repository,

Note: This project is not done yet,

**Comment by mikrotickets** [comment]
if it is a new droplet ubuntu 20.04 lts

**Comment by mendylivium** [comment]
Change it to **Ubuntu 22.04**

**Comment by mikrotickets** [comment]
I’ve just worked out it was due to a lack of memory on the Droplet, I upgraded from 512MB to 1GB , and it now installs fine



![image](https://user-images.githubusercontent.com/63126121/213038792-e7d312b2-96ef-45a9-8abe-068f91f2b2c6.png)
